services:
  - type: web
    name: lead-management-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: lead-management-db
          property: connectionString
      - key: DB_SSL
        value: "true"
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_ORIGIN
        sync: false

databases:
  - name: lead-management-db
    plan: free
